"""
子 Agent 3: PublisherAgent - 发布
负责把处理好的内容发布到目标平台。
第一版：生成 markdown 文件 + 本地保存。
"""
from __future__ import annotations
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Dict

from .base import BaseAgent, AgentResult
from ..config import config


CATEGORY_NAMES = {
    "ai_ml": "🤖 AI / 大模型",
    "devtools": "🛠️ 开发工具",
    "startup": "🚀 创业 / 融资",
    "research": "🔬 论文 / 研究",
    "general": "📌 综合",
}


class PublisherAgent(BaseAgent):
    name = "publisher"
    description = "把内容发布到目标平台（第一版：生成 markdown）"

    def run(self, items: List[Dict] = None, pipeline_name: str = "default") -> AgentResult:
        if not items:
            return AgentResult(success=True, data=[], items_processed=0)

        # 根据 pipeline 类型生成不同格式
        if pipeline_name == "ai_daily_cn":
            markdown = self._build_chinese_report(items, pipeline_name)
        elif pipeline_name == "ai_deepdive":
            markdown = self._build_deepdive_report(items, pipeline_name)
        elif pipeline_name == "scored_briefing":
            markdown = self._build_scored_report(items, pipeline_name)
        elif pipeline_name == "weekly_digest":
            markdown = self._build_weekly_report(items, pipeline_name)
        else:
            markdown = self._build_daily_report(items, pipeline_name)

        # 保存
        output_dir = Path("output")
        output_dir.mkdir(exist_ok=True)
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        output_file = output_dir / f"{pipeline_name}-{date_str}.md"
        output_file.write_text(markdown, encoding="utf-8")

        self.logger.info(f"已生成: {output_file}")

        return AgentResult(
            success=True,
            data={"file": str(output_file), "count": len(items)},
            items_processed=len(items),
        )

    def _build_daily_report(self, items: List[Dict], pipeline_name: str) -> str:
        """英文版日报"""
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines = [
            f"# {pipeline_name} Daily - {date_str}",
            "",
            f"> Auto-generated by AI Agent | {len(items)} items",
            "",
        ]
        lines.extend(self._group_by_category(items, use_chinese=False))
        lines.append("---")
        lines.append("*Auto-generated from public sources. For reference only.*")
        return "\n".join(lines)

    def _build_chinese_report(self, items: List[Dict], pipeline_name: str) -> str:
        """中文版日报"""
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines = [
            f"# 技术日报（中文版）- {date_str}",
            "",
            f"> 由 AI Agent 自动生成并翻译 | 共 {len(items)} 条",
            "",
        ]
        lines.extend(self._group_by_category(items, use_chinese=True))
        lines.append("---")
        lines.append("*本报告由 AI Agent 自动抓取公开信息并翻译生成，仅供参考。*")
        return "\n".join(lines)

    def _build_deepdive_report(self, items: List[Dict], pipeline_name: str) -> str:
        """深度分析版"""
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines = [
            f"># 🔥 今日热门深度分析 - {date_str}",
            "",
            f"> 由 AI Agent 自动精选并深度解读 | 共 {len(items)} 条",
            "",
        ]
        for i, item in enumerate(items, 1):
            lines.append(f"## {i}. {item.get('title', '无标题')}")
            lines.append(f"🔗 [{item.get('url', '')}]({item.get('url', '')})")
            lines.append("")
            lines.append(f"**摘要：** {item.get('summary', '')}")
            lines.append("")
            lines.append(f"**深度分析：**")
            lines.append(item.get("deep_analysis", ""))
            lines.append("")
        lines.append("---")
        lines.append("*深度分析由 AI 生成，仅供参考。*")
        return "\n".join(lines)

    def _build_scored_report(self, items: List[Dict], pipeline_name: str) -> str:
        """AI 打分热门简报"""
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines = [
            f"# 🏆 AI 热度排行榜 Top 10 - {date_str}",
            "",
            f"> 由 AI 自动打分排序 | 共 {len(items)} 条入选",
            "",
        ]
        for i, item in enumerate(items, 1):
            score = item.get("score", 5.0)
            medal = "🥇" if i == 1 else "🥈" if i == 2 else "🥉" if i == 3 else f"{i}."
            lines.append(f"## {medal} {item.get('title', '无标题')}  (⭐ {score}/10)")
            lines.append(f"🔗 [{item.get('source', '')}]({item.get('url', '')})")
            lines.append("")
            lines.append(f"{item.get('summary', '')}")
            lines.append("")
        lines.append("---")
        lines.append("*热度分由 AI 模型评估，仅供参考。*")
        return "\n".join(lines)

    def _build_weekly_report(self, items: List[Dict], pipeline_name: str) -> str:
        """每周精选周报（汇总版）"""
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines = [
            f"# 📊 每周技术精选周报 - {date_str}",
            "",
            f"> 由 AI Agent 自动汇总整理 | 共 {len(items)} 条精选",
            "",
            "## 🎯 本周概览",
            "",
            f"- 精选内容：{len(items)} 条",
            f"- 数据来源：Hacker News / Lobsters / ArXiv / GitHub Trending",
            f"- 生成时间：{date_str}",
            "",
            "## 📝 精选内容",
            "",
        ]
        lines.extend(self._group_by_category(items, use_chinese=False))
        lines.append("")
        lines.append("---")
        lines.append("*本周报由 AI 自动汇总生成，精选自公开技术社区。*")
        return "\n".join(lines)

    def _group_by_category(self, items: List[Dict], use_chinese: bool = False) -> List[str]:
        """按分类分组输出"""
        by_cat = {}
        for item in items:
            cat = item.get("category", "general")
            by_cat.setdefault(cat, []).append(item)

        lines = []
        for cat, cat_items in by_cat.items():
            cat_name = CATEGORY_NAMES.get(cat, cat)
            lines.append(f"## {cat_name}")
            lines.append("")
            for i, item in enumerate(cat_items, 1):
                title = item.get("title_cn", item.get("title", "")) if use_chinese else item.get("title", "")
                url = item.get("url", "")
                summary = item.get("summary_cn", item.get("summary", "")) if use_chinese else item.get("summary", "")
                source = item.get("source", "")
                lines.append(f"### {i}. [{title}]({url})")
                lines.append(f"*{source}*")
                lines.append(f"{summary}")
                lines.append("")
        return lines
