"""
子 Agent 3: PublisherAgent - 发布
负责把处理好的内容发布到目标平台。
第一版：生成 markdown 文件 + 本地保存。
"""
from __future__ import annotations
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Dict

from .base import BaseAgent, AgentResult
from ..config import config


CATEGORY_NAMES = {
    "ai_ml": "🤖 AI / 大模型",
    "devtools": "🛠️ 开发工具",
    "startup": "🚀 创业 / 融资",
    "research": "🔬 论文 / 研究",
    "general": "📌 综合",
}


class PublisherAgent(BaseAgent):
    name = "publisher"
    description = "把内容发布到目标平台（第一版：生成 markdown）"

    def run(self, items: List[Dict] = None, pipeline_name: str = "default") -> AgentResult:
        if not items:
            return AgentResult(success=True, data=[], items_processed=0)

        # 根据 pipeline 类型生成不同格式
        if pipeline_name == "ai_daily_cn":
            markdown = self._build_chinese_report(items, pipeline_name)
        elif pipeline_name == "ai_deepdive":
            markdown = self._build_deepdive_report(items, pipeline_name)
        elif pipeline_name == "scored_briefing":
            markdown = self._build_scored_report(items, pipeline_name)
        elif pipeline_name == "weekly_digest":
            markdown = self._build_weekly_report(items, pipeline_name)
        elif pipeline_name == "reddit_digest":
            markdown = self._build_reddit_report(items, pipeline_name)
        elif pipeline_name == "github_tools":
            markdown = self._build_tools_report(items, pipeline_name)
        elif pipeline_name == "free_ai_tools":
            markdown = self._build_free_tools_report(items, pipeline_name)
        elif pipeline_name == "ai_prompts":
            markdown = self._build_prompts_report(items, pipeline_name)
        elif pipeline_name == "product_hunt_daily":
            markdown = self._build_ph_report(items, pipeline_name)
        elif pipeline_name == "devto_daily":
            markdown = self._build_devto_report(items, pipeline_name)
        elif pipeline_name == "dev_tips_daily":
            markdown = self._build_tips_report(items, pipeline_name)
        elif pipeline_name == "ai_qa_daily":
            markdown = self._build_qa_report(items, pipeline_name)
        else:
            markdown = self._build_daily_report(items, pipeline_name)

        # 保存
        output_dir = Path("output")
        output_dir.mkdir(exist_ok=True)
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        output_file = output_dir / f"{pipeline_name}-{date_str}.md"
        output_file.write_text(markdown, encoding="utf-8")

        self.logger.info(f"已生成: {output_file}")

        return AgentResult(
            success=True,
            data={"file": str(output_file), "count": len(items)},
            items_processed=len(items),
        )

    def _build_daily_report(self, items: List[Dict], pipeline_name: str) -> str:
        """英文版日报"""
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines = [
            f"# {pipeline_name} Daily - {date_str}",
            "",
            f"> Auto-generated by AI Agent | {len(items)} items",
            "",
        ]
        lines.extend(self._group_by_category(items, use_chinese=False))
        lines.append("---")
        lines.append("*Auto-generated from public sources. For reference only.*")
        return "\n".join(lines)

    def _build_chinese_report(self, items: List[Dict], pipeline_name: str) -> str:
        """中文版日报"""
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines = [
            f"# 技术日报（中文版）- {date_str}",
            "",
            f"> 由 AI Agent 自动生成并翻译 | 共 {len(items)} 条",
            "",
        ]
        lines.extend(self._group_by_category(items, use_chinese=True))
        lines.append("---")
        lines.append("*本报告由 AI Agent 自动抓取公开信息并翻译生成，仅供参考。*")
        return "\n".join(lines)

    def _build_deepdive_report(self, items: List[Dict], pipeline_name: str) -> str:
        """深度分析版"""
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines = [
            f"># 🔥 今日热门深度分析 - {date_str}",
            "",
            f"> 由 AI Agent 自动精选并深度解读 | 共 {len(items)} 条",
            "",
        ]
        for i, item in enumerate(items, 1):
            lines.append(f"## {i}. {item.get('title', '无标题')}")
            lines.append(f"🔗 [{item.get('url', '')}]({item.get('url', '')})")
            lines.append("")
            lines.append(f"**摘要：** {item.get('summary', '')}")
            lines.append("")
            lines.append(f"**深度分析：**")
            lines.append(item.get("deep_analysis", ""))
            lines.append("")
        lines.append("---")
        lines.append("*深度分析由 AI 生成，仅供参考。*")
        return "\n".join(lines)

    def _build_scored_report(self, items: List[Dict], pipeline_name: str) -> str:
        """AI 打分热门简报"""
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines = [
            f"# 🏆 AI 热度排行榜 Top 10 - {date_str}",
            "",
            f"> 由 AI 自动打分排序 | 共 {len(items)} 条入选",
            "",
        ]
        for i, item in enumerate(items, 1):
            score = item.get("score", 5.0)
            medal = "🥇" if i == 1 else "🥈" if i == 2 else "🥉" if i == 3 else f"{i}."
            lines.append(f"## {medal} {item.get('title', '无标题')}  (⭐ {score}/10)")
            lines.append(f"🔗 [{item.get('source', '')}]({item.get('url', '')})")
            lines.append("")
            lines.append(f"{item.get('summary', '')}")
            lines.append("")
        lines.append("---")
        lines.append("*热度分由 AI 模型评估，仅供参考。*")
        return "\n".join(lines)

    def _build_weekly_report(self, items: List[Dict], pipeline_name: str) -> str:
        """每周精选周报（汇总版）"""
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines = [
            f"# 📊 每周技术精选周报 - {date_str}",
            "",
            f"> 由 AI Agent 自动汇总整理 | 共 {len(items)} 条精选",
            "",
            "## 🎯 本周概览",
            "",
            f"- 精选内容：{len(items)} 条",
            f"- 数据来源：Hacker News / Lobsters / ArXiv / GitHub Trending",
            f"- 生成时间：{date_str}",
            "",
            "## 📝 精选内容",
            "",
        ]
        lines.extend(self._group_by_category(items, use_chinese=False))
        lines.append("")
        lines.append("---")
        lines.append("*本周报由 AI 自动汇总生成，精选自公开技术社区。*")
        return "\n".join(lines)

    def _build_reddit_report(self, items: List[Dict], pipeline_name: str) -> str:
        """Reddit 技术社区热门 digest"""
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines = [
            f"# 💬 Reddit 技术社区热门帖 - {date_str}",
            "",
            f"> 由 AI Agent 自动抓取并摘要 | 共 {len(items)} 条热门",
            "",
            "## 🔥 本周热议",
            "",
        ]
        for i, item in enumerate(items, 1):
            source = item.get("source", "")
            lines.append(f"### {i}. [{item.get('title', '')}]({item.get('url', '')})")
            lines.append(f"*{source}*")
            lines.append("")
            if item.get("summary"):
                lines.append(item.get("summary", ""))
                lines.append("")
        lines.append("---")
        lines.append("*内容来自 Reddit 公开社区，由 AI 自动摘要生成。*")
        return "\n".join(lines)

    def _build_tools_report(self, items: List[Dict], pipeline_name: str) -> str:
        """GitHub 实用工具推荐"""
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines = [
            f"# 🛠️ 今日值得试的开源工具 - {date_str}",
            "",
            f"> 精选自 GitHub Trending | AI 帮你筛掉水项目，只留实用的 | 共 {len(items)} 个",
            "",
        ]
        for i, item in enumerate(items, 1):
            lines.append(f"## {i}. [{item.get('title', '')}]({item.get('url', '')})")
            lines.append("")
            why = item.get("why_useful", "")
            if why:
                lines.append(f"**💡 为什么值得试：** {why}")
                lines.append("")
            if item.get("summary"):
                lines.append(f"*项目描述：* {item.get('summary', '')[:200]}...")
                lines.append("")
        lines.append("---")
        lines.append("*觉得有用？点个 ⭐ Star 支持一下原作者。*")
        return "\n".join(lines)

    def _build_free_tools_report(self, items: List[Dict], pipeline_name: str) -> str:
        """免费 AI 工具汇总"""
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines = [
            f"# 🆓 今日免费 AI 工具汇总 - {date_str}",
            "",
            f"> 精选免费好用的 AI 工具 | AI 帮你筛过，只留真正有用的 | 共 {len(items)} 个",
            "",
        ]
        for i, item in enumerate(items, 1):
            lines.append(f"## {i}. [{item.get('title', '')}]({item.get('url', '')})")
            lines.append("")
            who = item.get("who_for", "")
            if who:
                lines.append(f"**👥 适合谁：** {who}")
                lines.append("")
            how = item.get("how_to_start", "")
            if how:
                lines.append(f"**🚀 怎么开始：** {how}")
                lines.append("")
            if item.get("summary"):
                lines.append(f"**📝 简介：** {item.get('summary', '')}")
                lines.append("")
        lines.append("---")
        lines.append("*收藏起来，慢慢试！觉得有用记得分享给朋友~*")
        return "\n".join(lines)

    def _build_prompts_report(self, items: List[Dict], pipeline_name: str) -> str:
        """每日 AI Prompt 技巧汇总"""
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines = [
            f"# ✨ 每日 AI Prompt 技巧 - {date_str}",
            "",
            f"> 从今天的 AI 圈热点里提炼出来的实用 Prompt 技巧 | 共 {len(items)} 条",
            "",
        ]
        for i, item in enumerate(items, 1):
            lines.append(f"## {i}. 💡 技巧 {i}")
            lines.append("")
            tip = item.get("prompt_tip", "")
            if tip:
                lines.append(f"**{tip}**")
                lines.append("")
            lines.append(f"📎 来源：[{item.get('title', '')}]({item.get('url', '')})")
            lines.append("")
        lines.append("---")
        lines.append("*试试这些技巧，你的 AI 输出质量会肉眼可见地提升！*")
        return "\n".join(lines)

    def _build_ph_report(self, items: List[Dict], pipeline_name: str) -> str:
        """Product Hunt 每日新品推荐"""
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines = [
            f"# 🚀 今日 Product Hunt 新品 - {date_str}",
            "",
            f"> 精选今天上线的新产品 | AI 帮你筛过，只留有意思的 | 共 {len(items)} 个",
            "",
        ]
        for i, item in enumerate(items, 1):
            lines.append(f"## {i}. [{item.get('title', '')}]({item.get('url', '')})")
            lines.append("")
            what = item.get("what_is_it", "")
            if what:
                lines.append(f"**💡 是什么 + 为什么值得试：** {what}")
                lines.append("")
            lines.append("---")
        lines.append("*想发现更多新奇产品，记得每天来看看~*")
        return "\n".join(lines)

    def _build_devto_report(self, items: List[Dict], pipeline_name: str) -> str:
        """Dev.to 热门技术文章精选"""
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines = [
            f"# 📚 Dev.to 热门技术文章 - {date_str}",
            "",
            f"> 从 Dev.to 社区精选的高质量技术文章 | AI 帮你提炼精华 | 共 {len(items)} 篇",
            "",
        ]
        for i, item in enumerate(items, 1):
            lines.append(f"## {i}. [{item.get('title', '')}]({item.get('url', '')})")
            lines.append("")
            if item.get("summary"):
                lines.append(f"**✨ 精华总结：** {item.get('summary', '')}")
                lines.append("")
        lines.append("---")
        lines.append("*读完有收获？点个赞支持一下原作者~*")
        return "\n".join(lines)

    def _build_tips_report(self, items: List[Dict], pipeline_name: str) -> str:
        """每日开发技巧汇总"""
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines = [
            f"# 💡 每日开发技巧 - {date_str}",
            "",
            f"> 每天学一个实用技巧，效率慢慢提上来 | 共 {len(items)} 条",
            "",
        ]
        for i, item in enumerate(items, 1):
            lines.append(f"## 技巧 {i}")
            lines.append("")
            lines.append(f"**{item.get('title', '')}**")
            lines.append("")
            if item.get("summary"):
                lines.append(f"✨ {item.get('summary', '')}")
                lines.append("")
            lines.append(f"📎 [阅读原文]({item.get('url', '')})")
            lines.append("")
        lines.append("---")
        lines.append("*每天一个小技巧，一年就是 365 个进步~*")
        return "\n".join(lines)

    def _build_qa_report(self, items: List[Dict], pipeline_name: str) -> str:
        """每日 AI 问答"""
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines = [
            f"# ❓ 每日 AI 问答 - {date_str}",
            "",
            f"> 关于 AI 你可能想问的问题 | 每天一个问题，搞懂一个概念",
            "",
        ]
        for i, item in enumerate(items, 1):
            title = item.get("title", "")
            lines.append(f"## Q{i}: {title}？")
            lines.append("")
            lines.append(f"**A:** {item.get('summary', '')}")
            lines.append("")
            lines.append(f"📎 更多阅读：[{title}]({item.get('url', '')})")
            lines.append("")
        lines.append("---")
        lines.append("*有问题想问？欢迎在 GitHub 提 Issue~*")
        return "\n".join(lines)

    def _group_by_category(self, items: List[Dict], use_chinese: bool = False) -> List[str]:
        """按分类分组输出"""
        by_cat = {}
        for item in items:
            cat = item.get("category", "general")
            by_cat.setdefault(cat, []).append(item)

        lines = []
        for cat, cat_items in by_cat.items():
            cat_name = CATEGORY_NAMES.get(cat, cat)
            lines.append(f"## {cat_name}")
            lines.append("")
            for i, item in enumerate(cat_items, 1):
                title = item.get("title_cn", item.get("title", "")) if use_chinese else item.get("title", "")
                url = item.get("url", "")
                summary = item.get("summary_cn", item.get("summary", "")) if use_chinese else item.get("summary", "")
                source = item.get("source", "")
                lines.append(f"### {i}. [{title}]({url})")
                lines.append(f"*{source}*")
                lines.append(f"{summary}")
                lines.append("")
        return lines
